web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes_from:
    - code
  links:
    - php
php:
  image: nas1k/php56-fpm
  volumes_from:
    - code
  links:
    - db
db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: abcABC123
    MYSQL_USER: mysql_user
    MYSQL_DATABASE: mage
    MYSQL_PASSWORD: password
  volumes_from:
    - seed
code:
  image: busybox
  volumes:
    - ./.devops/vhosts/mage.conf:/etc/nginx/conf.d/mage.conf
    - ./src/atb-ecomm.mage:/var/www/html
    - ./devops/config/local.xml:/var/www/html/public-web/app/etc/local.xml
seed:
  image: busybox
  volumes:
    - ./src/seed:/seed